#!/bin/bash

# Dynamic Folder Icon Colors based on Matugen Color Scheme
# This script automatically picks the best Yaru icon color variant
# based on your wallpaper's color scheme generated by matugen

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_msg() {
    echo -e "${BLUE}[*]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

# Function to convert hex to RGB
hex_to_rgb() {
    local hex=$1
    # Remove # if present
    hex=${hex#\#}
    
    # Convert to RGB
    r=$((16#${hex:0:2}))
    g=$((16#${hex:2:2}))
    b=$((16#${hex:4:2}))
    
    echo "$r $g $b"
}

# Function to determine which color component is dominant
get_dominant_color() {
    local hex=$1
    read r g b <<< $(hex_to_rgb "$hex")
    
    # Determine which color is dominant
    if [ $g -gt $r ] && [ $g -gt $b ]; then
        # Green dominant
        if [ $b -gt $r ]; then
            echo "cyan"
        else
            echo "green"
        fi
    elif [ $b -gt $r ] && [ $b -gt $g ]; then
        # Blue dominant
        if [ $r -gt $g ]; then
            echo "purple"
        else
            echo "blue"
        fi
    elif [ $r -gt $g ] && [ $r -gt $b ]; then
        # Red dominant
        if [ $g -gt $b ]; then
            echo "orange"
        elif [ $b -gt $g ]; then
            echo "magenta"
        else
            echo "red"
        fi
    else
        # Balanced or muted colors
        if [ $r -eq $g ] && [ $g -eq $b ]; then
            echo "dark"
        else
            echo "sage"
        fi
    fi
}

# Function to map color to Yaru variant
map_to_yaru_variant() {
    local color=$1
    
    case $color in
        green)
            echo "Yaru-olive"
            ;;
        cyan)
            echo "Yaru-prussiangreen"
            ;;
        blue)
            echo "Yaru-blue"
            ;;
        purple)
            echo "Yaru-purple"
            ;;
        magenta)
            echo "Yaru-magenta"
            ;;
        red)
            echo "Yaru-red"
            ;;
        orange)
            echo "Yaru-wartybrown"
            ;;
        sage)
            echo "Yaru-olive"
            ;;
        dark)
            echo "Yaru-dark"
            ;;
        *)
            echo "Yaru-olive"
            ;;
    esac
}

# Check if matugen config exists (try multiple locations)
MATUGEN_COLORS="$HOME/.config/matugen/colors.json"
HYPR_COLORS="$HOME/.config/hypr/colors.conf"

# Try colors.json first, then fall back to hyprland colors.conf
if [ -f "$MATUGEN_COLORS" ]; then
    print_msg "Reading matugen color scheme from colors.json..."
    SOURCE_FILE="$MATUGEN_COLORS"
    USE_JSON=true
elif [ -f "$HYPR_COLORS" ]; then
    print_msg "Reading matugen color scheme from hyprland colors.conf..."
    SOURCE_FILE="$HYPR_COLORS"
    USE_JSON=false
else
    print_error "Matugen colors not found"
    print_msg "Run matugen first to generate colors from your wallpaper"
    exit 1
fi

# Extract primary color from matugen
PRIMARY_COLOR=""

if [ "$USE_JSON" = true ]; then
    # Try to extract primary color using jq if available
    if command -v jq &> /dev/null; then
        # Try different possible paths in the JSON
        PRIMARY_COLOR=$(jq -r '.colors.primary // .colors.primary_container // .colors.primary_fixed // empty' "$MATUGEN_COLORS" 2>/dev/null)
        
        # If still empty, try to get any prominent color
        if [ -z "$PRIMARY_COLOR" ] || [ "$PRIMARY_COLOR" = "null" ]; then
            PRIMARY_COLOR=$(jq -r '.colors | to_entries | .[0].value // empty' "$MATUGEN_COLORS" 2>/dev/null)
        fi
    else
        # Fallback: use grep and sed
        PRIMARY_COLOR=$(grep -m1 '"primary"' "$MATUGEN_COLORS" | sed -E 's/.*"#([0-9A-Fa-f]{6})".*/\1/' | head -1)
        if [ -z "$PRIMARY_COLOR" ]; then
            PRIMARY_COLOR=$(grep -m1 '#[0-9A-Fa-f]\{6\}' "$MATUGEN_COLORS" | sed -E 's/.*"#([0-9A-Fa-f]{6})".*/\1/' | head -1)
        fi
    fi
else
    # Extract from hyprland colors.conf
    PRIMARY_COLOR=$(grep '^\$primary ' "$HYPR_COLORS" | sed -E 's/.*rgba\(([0-9a-fA-F]{6,8})[^\)]*\).*/\1/' | head -1)
    # Remove alpha channel if present (last 2 chars)
    if [ ${#PRIMARY_COLOR} -eq 8 ]; then
        PRIMARY_COLOR=${PRIMARY_COLOR:0:6}
    fi
fi

# Ensure we have a valid hex color
if [ -z "$PRIMARY_COLOR" ] || [ "$PRIMARY_COLOR" = "null" ]; then
    print_error "Could not extract color from matugen"
    print_msg "Defaulting to Yaru-olive (green)"
    ICON_THEME="Yaru-olive"
else
    # Remove # if present
    PRIMARY_COLOR=${PRIMARY_COLOR#\#}
    
    print_msg "Primary color: #$PRIMARY_COLOR"
    
    # Determine dominant color
    DOMINANT=$(get_dominant_color "$PRIMARY_COLOR")
    print_msg "Dominant color: $DOMINANT"
    
    # Map to Yaru variant
    ICON_THEME=$(map_to_yaru_variant "$DOMINANT")
fi

print_msg "Selected icon theme: $ICON_THEME"

# Apply the icon theme
print_msg "Applying icon theme..."

# Update GTK 3.0
if [ -f "$HOME/.config/gtk-3.0/settings.ini" ]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$ICON_THEME/" "$HOME/.config/gtk-3.0/settings.ini"
else
    mkdir -p "$HOME/.config/gtk-3.0"
    cat > "$HOME/.config/gtk-3.0/settings.ini" << EOF
[Settings]
gtk-icon-theme-name=$ICON_THEME
gtk-theme-name=Adwaita-dark
gtk-application-prefer-dark-theme=1
EOF
fi

# Update GTK 4.0
if [ -f "$HOME/.config/gtk-4.0/settings.ini" ]; then
    sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$ICON_THEME/" "$HOME/.config/gtk-4.0/settings.ini"
else
    mkdir -p "$HOME/.config/gtk-4.0"
    cat > "$HOME/.config/gtk-4.0/settings.ini" << EOF
[Settings]
gtk-icon-theme-name=$ICON_THEME
gtk-theme-name=Adwaita-dark
gtk-application-prefer-dark-theme=1
EOF
fi

# Apply via gsettings if available
if command -v gsettings &> /dev/null; then
    gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME" 2>/dev/null || true
fi

print_success "Icon theme applied: $ICON_THEME"
print_msg "Restart Nautilus to see changes: killall nautilus"

# Send notification if notify-send is available
if command -v notify-send &> /dev/null; then
    notify-send "Folder Icons Updated" "Now using: $ICON_THEME\nBased on wallpaper colors" -t 3000
fi
